version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres17
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  migrate:
    image: migrate/migrate
    # SELinux флаг :Z для Fedora
    volumes:
      - ./internal/db/migrations:/migrations:Z
    working_dir: /migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}?sslmode=${PG_SSLMODE}",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
