// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeleteTask(ctx context.Context, id string) error
	GetAllTasks(ctx context.Context) ([]Task, error)
	GetTaskByID(ctx context.Context, id string) (Task, error)
	GetTasksByStatus(ctx context.Context, status string) ([]Task, error)
	GetTasksDueBetween(ctx context.Context, arg GetTasksDueBetweenParams) ([]Task, error)
	SaveTask(ctx context.Context, arg SaveTaskParams) error
}

var _ Querier = (*Queries)(nil)
