// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"
)

type Querier interface {
	DeleteTask(ctx context.Context, id string) error
	GetAllTasks(ctx context.Context) ([]Task, error)
	GetOverdueTasks(ctx context.Context) ([]Task, error)
	GetSortedTasks(ctx context.Context, arg GetSortedTasksParams) ([]Task, error)
	GetTaskByID(ctx context.Context, id string) (Task, error)
	GetTasksByStatus(ctx context.Context, status string) ([]Task, error)
	GetTasksDueThisWeek(ctx context.Context) ([]Task, error)
	GetTasksDueToday(ctx context.Context) ([]Task, error)
	SaveTask(ctx context.Context, arg SaveTaskParams) error
}

var _ Querier = (*Queries)(nil)
