// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1) {
  return window['go']['wails']['TaskHandler']['CompleteTask'](arg1);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['wails']['TaskHandler']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['wails']['TaskHandler']['DeleteTask'](arg1);
}

export function GetDashboard() {
  return window['go']['wails']['TaskHandler']['GetDashboard']();
}

export function GetTask(arg1) {
  return window['go']['wails']['TaskHandler']['GetTask'](arg1);
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['wails']['TaskHandler']['ListTasks'](arg1, arg2, arg3);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['TaskHandler']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}
