// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {app} from '../models';

export function CompleteTask(arg1:string):Promise<void>;

export function CreateTask(arg1:string,arg2:string,arg3:time.Time):Promise<app.CreateTaskOutput>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetDashboard():Promise<app.GetDashboardOutput>;

export function GetTask(arg1:string):Promise<app.GetTaskOutput>;

export function ListTasks(arg1:any,arg2:any,arg3:any):Promise<app.ListTasksOutput>;

export function UpdateTask(arg1:string,arg2:any,arg3:any,arg4:any,arg5:time.Time):Promise<void>;
