// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTaskFromFrontend(arg1) {
  return window['go']['main']['App']['AddTaskFromFrontend'](arg1);
}

export function DeleteTaskFromFrontend(arg1) {
  return window['go']['main']['App']['DeleteTaskFromFrontend'](arg1);
}

export function GetTasksFromFrontend() {
  return window['go']['main']['App']['GetTasksFromFrontend']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MarkTaskCompletedFromFrontend(arg1) {
  return window['go']['main']['App']['MarkTaskCompletedFromFrontend'](arg1);
}
