// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddTaskFromFrontend(arg1:string):Promise<domain.Task>;

export function DeleteTaskFromFrontend(arg1:string):Promise<void>;

export function GetTasksFromFrontend():Promise<Array<domain.Task>>;

export function Greet(arg1:string):Promise<string>;

export function MarkTaskCompletedFromFrontend(arg1:string):Promise<void>;
